# Generated by Django 2.0.4 on 2018-04-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_burrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='burrower',
            new_name='borrower',
        ),
    ]
